# This file was generated by GoReleaser. DO NOT EDIT.
cask "nibble" do
  name "nibble"
  desc "Fast local network scanner with hardware identification and a terminal UI"
  homepage "https://github.com/backendsystems/nibble"
  version "0.4.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nibble"

  on_macos do
    on_intel do
      url "https://github.com/backendsystems/nibble/releases/download/v#{version}/nibble_darwin_amd64.tar.gz"
      sha256 "52ece9632e88be78da134a2860dba8cbb429ba3e8388f12b27070495d6a353de"
    end
    on_arm do
      url "https://github.com/backendsystems/nibble/releases/download/v#{version}/nibble_darwin_arm64.tar.gz"
      sha256 "76a8fc4e6b8a97ac5419fe989c3276e354ca4d5b9ccc9a2bb09e14e11386094a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/backendsystems/nibble/releases/download/v#{version}/nibble_linux_amd64.tar.gz"
      sha256 "e849b597913d353ec01e618c5a7b8a46ffbfc5e207e2285f00c39a04afd2f319"
    end
    on_arm do
      url "https://github.com/backendsystems/nibble/releases/download/v#{version}/nibble_linux_arm64.tar.gz"
      sha256 "83b89eafb1c5f1ac3324b4003cf9b50090ceb365c13c2ff2d950fd1fded92092"
    end
  end

  # No zap stanza required
end
